import type { Audience } from '../lib/types';

export const AUDIENCE_DESCRIPTIONS: Record<Audience, string> = {
  teen: `Gen Z based in Singapore (born ~2007-2008), just finished JC / poly / O-levels or in early ITE/JC/polytechnic, on a long break. Lives at home (HDB or condo), often near MRT. Limited pocket money — S$0-30 per outing typical. Locally fluent: knows the MRT lines, hawker centres, ActiveSG, NLB branches, Park Connectors, the difference between kopi-o and kopi-c kosong. Cultural fluency mix: grew up on Pokemon, Beyblade, K-drama, anime, Cartoon Network, Studio Ghibli, Indian-Singaporean teens know Bollywood and Tamil cinema too. Mix of leisure desire and pressure about the future (uni admissions, NS for the guys, picking a poly course, parents asking what next).`,
  adult: `Working professional in Singapore, ~26-35. Lives in HDB / rental condo / shared apartment. Disposable income S$3000-8000/month after CPF and rent, but time-scarce. Has Saturday/Sunday + occasional 2-4 hour weekday-evening idle pockets. Defaults to phone, streaming, food delivery when bored. Wants the idle time to feel intentional — hobbies they keep meaning to start, friends they keep meaning to call, errands deferred, half-finished side projects. Familiar with: MRT, EZ-Link, F&B-heavy social culture, Park Connectors, hawker culture, the ArtScience / NMS / NGS, ActiveSG, indoor climbing gyms, Tiong Bahru / Joo Chiat / Holland V / Tanjong Pagar / CBD weekend life.`,
};

export const SEED_THEMES: Record<Audience, string[]> = {
  teen: [
    `Hawker + heartland (S$0-15): Maxwell / Old Airport Road / Adam Road / Ghim Moh / Tiong Bahru Market food adventures, kopi-o + kaya toast at void-deck kopitiam, chendol or ice kachang run, ondeh-ondeh from a Geylang Serai stall, ramen at Tampines, ramly burger by the void deck. Real prices.`,
    `Outdoor + Park Connectors (S$0-15): East Coast Park sunrise, Marina Barrage rooftop, Pulau Ubin bumboat + bike rental, MacRitchie boardwalk, Henderson Waves, Southern Ridges, Bishan-AMK Park, Coney Island walk, Punggol Waterway cycle, Lazarus Island day trip. Include actual rental + transport costs.`,
    `Sentosa, RWS + paid attractions (S$10-50): Sentosa boardwalk + beach picnic, Wings of Time, Skyline Luge, Mega Adventure zip-line, S.E.A. Aquarium, Adventure Cove waterpark, Universal Studios Singapore day, Trick Eye Museum, iFly indoor skydive. Be specific about ticket prices, include MRT fare.`,
    `Zoo, River Wonders, Bird Paradise (S$25-50): Singapore Zoo (~S$48), River Wonders (~S$42), Bird Paradise (~S$45), Night Safari (~S$55), combo passes from Mandai. Half-day plans, what to do first, where to eat after.`,
    `Restaurants + cafés (S$8-50): Hai Di Lao hotpot (~S$40 share), Burnt Ends lunch counter (~S$35), Hawker Chan Soya Sauce Chicken (~S$8), café-hopping in Tiong Bahru (Tiong Bahru Bakery, Plain Vanilla, Forty Hands, ~S$12), brunch at Common Man Coffee Roasters, ramen at Tonkotsu King.`,
    `Creative + nostalgic (mostly free): doodle to one Drake album, design a fake Pokemon gym leader card, recreate a Studio Ghibli scene as a comic, write 3 pages of a JC short story, photograph one HDB block in 20 stills, recreate childhood drawings, make a Tampines / Tampopo / Tiong Bahru playlist.`,
    `Skill + study prep (free): one Codeforces / LeetCode easy problem, 25-min Forest sprint on JC prelims, build a one-page portfolio on Vercel, 10 Mandarin / Malay / Tamil phrases on Duolingo, IPPT chin-up training, the Cambridge Latin tutor on YouTube.`,
    `Social + mindful (S$0-15): call your secondary school best friend, organise a kopitiam meetup at AMK, board games at a friend's HDB, video call a cousin in KL, sit on the void deck with a friend and chendol, journal at Bishan Park, dawn walk before the heat.`,
  ],
  adult: [
    `Hawker + neighbourhood (S$5-20): lunch hunt at Maxwell / Tiong Bahru / Tanjong Pagar Plaza / Amoy Street / Ghim Moh, solo dinner at Old Airport Road, Joo Chiat Peranakan walk + Katong laksa, breakfast at Tiong Bahru Bakery, weeknight zi char in Chinatown. Real S$ all-in.`,
    `Outdoor + active (S$0-30): Park Connector cycle with SG Bike, East Coast Park sunset, ActiveSG swim or gym (~S$1.50), Sentosa boardwalk, climbing day pass at Boruca/BFF/Climb Central (~S$30), Bukit Timah hike, Botanic Gardens picnic, sunrise paddle at MacRitchie.`,
    `Sentosa, RWS + paid attractions (S$25-50): Sentosa beach club lunch, Universal Studios half-day, S.E.A. Aquarium afternoon, Wings of Time, Adventure Cove, Skyline Luge night session, Cable Car ride at sunset. Include transit, entry, one meal.`,
    `Singapore Zoo & wildlife parks (S$30-50): Singapore Zoo half-day (~S$48), Night Safari (~S$55), River Wonders (~S$42), Bird Paradise (~S$45). Include transport from MRT + lunch nearby.`,
    `Restaurants + bars + omakase (S$15-50): Hai Di Lao hotpot, Burnt Ends, Long Beach seafood, omakase under S$50 (Sushiro / Sushi Bar Maru / Hashida lunch), wine bar at Tanjong Pagar, dessert at Janice Wong, rooftop drinks at LeVeL33, kopi at Common Man.`,
    `Culture + curiosity (S$0-30): free museum afternoon (NMS, NGS, ArtScience on permanent), a play at Esplanade outdoor, The Projector film off-peak (~S$10), Bras Basah library random-book hour, ArtScience Future World (~S$25), Cloud Forest at Gardens by the Bay (~S$20).`,
    `Hobbies + skills (mostly free): 20 pages of the bedside book, one piano practice, the recipe you bookmarked 3 months ago, the half-finished side project, an Italian phrase lesson, one online Coursera lecture.`,
    `Social + low-effort wellness (S$0-25): voice-note one friend you owe, a 25-min real phone call to a cousin, host a weekday dinner with one specific person, 10-min stretch, sunlight on the balcony, prep a healthy lunchbox, sort one drawer in the HDB.`,
  ],
};
